app_identifier "com.liuqingyue.EnglishSprout"
metadata_path File.expand_path("fastlane/metadata", Dir.pwd)
screenshots_path File.expand_path("fastlane/screenshots", Dir.pwd)
submit_for_review false
automatic_release false
force true
skip_binary_upload true
skip_screenshots true
run_precheck_before_submit false
precheck_include_in_app_purchases false
