app_identifier "com.liuqingyue.EnglishSprout"
metadata_path File.expand_path("metadata", __dir__)
screenshots_path File.expand_path("screenshots", __dir__)
submit_for_review false
automatic_release false
force true
skip_binary_upload true
skip_screenshots true
run_precheck_before_submit false
precheck_include_in_app_purchases false
